"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const machineController_1 = require('../controllers/machineController.cjs');
const rateLimiter_1 = require('../middlewares/rateLimiter.cjs');
const router = (0, express_1.Router)();
router.get("/", rateLimiter_1.machineRateLimiter, machineController_1.getAllMachines);
router.get("/filter", rateLimiter_1.machineRateLimiter, machineController_1.filterMachines);
router.get("/category/:category", rateLimiter_1.machineRateLimiter, machineController_1.getMachinesByCategory);
router.get("/difficulty/:difficulty", rateLimiter_1.machineRateLimiter, machineController_1.getMachinesByDifficulty);
router.get("/target/:target", rateLimiter_1.machineRateLimiter, machineController_1.getMachinesByTarget);
router.get("/:id", rateLimiter_1.machineRateLimiter, machineController_1.getMachineById);
router.post("/", rateLimiter_1.machineRateLimiter, machineController_1.createMachine);
router.put("/:id", rateLimiter_1.machineRateLimiter, machineController_1.updateMachine);
router.delete("/:id", rateLimiter_1.machineRateLimiter, machineController_1.deleteMachine);
exports.default = router;
