"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const workoutController_1 = require("../controllers/workoutController.cjs");
const goalController_1 = require("../controllers/goalController.cjs");
const auth_1 = require("../middlewares/auth.cjs");
const rateLimiter_1 = require("../middlewares/rateLimiter.cjs");
const router = (0, express_1.Router)();
const workoutController = new workoutController_1.WorkoutController();
const goalController = new goalController_1.GoalController();
router.get("/plans", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), workoutController.getUserPlans);
router.post("/plans", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.createPlan);
router.put("/plans/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.updatePlan);
router.delete("/plans/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.deletePlan);
router.get("/sessions", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), workoutController.getUserSessions);
router.post("/sessions", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.startSession);
router.post("/sessions/:id/complete", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.completeSession);
router.get("/goals", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), goalController.getGoals.bind(goalController));
router.get("/goals/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), goalController.getGoal.bind(goalController));
router.post("/goals", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), goalController.createGoal.bind(goalController));
router.put("/goals/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), goalController.updateGoal.bind(goalController));
router.delete("/goals/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), goalController.deleteGoal.bind(goalController));
router.get("/progress", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), workoutController.getProgress);
exports.default = router;
