"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.toLikeDTOList = exports.toLikeEntity = exports.toLikeDTO = exports.toUserLevelDTOList = exports.toUserLevelEntity = exports.toUserLevelDTO = exports.toExpHistoryDTOList = exports.toExpHistoryEntity = exports.toExpHistoryDTO = exports.toExerciseSetDTOList = exports.toExerciseSetEntity = exports.toExerciseSetDTO = exports.toWorkoutSessionDTOList = exports.toWorkoutSessionEntity = exports.toWorkoutSessionDTO = exports.toGymDTOList = exports.toGymEntity = exports.toGymDTO = exports.toCommentDTOList = exports.toCommentEntity = exports.toCommentDTO = exports.toPostDTOList = exports.toPostEntity = exports.toPostDTO = exports.toUserDTOList = exports.toUserEntity = exports.toUserDTO = exports.toMachineDTOList = exports.toMachineEntity = exports.toMachineDTO = exports.LikeTransformer = exports.UserLevelTransformer = exports.ExpHistoryTransformer = exports.ExerciseSetTransformer = exports.WorkoutSessionTransformer = exports.GymTransformer = exports.CommentTransformer = exports.PostTransformer = exports.UserTransformer = exports.MachineTransformer = void 0;
var machineTransformer_1 = require("./machineTransformer.cjs");
Object.defineProperty(exports, "MachineTransformer", { enumerable: true, get: function () { return machineTransformer_1.MachineTransformer; } });
var userTransformer_1 = require("./userTransformer.cjs");
Object.defineProperty(exports, "UserTransformer", { enumerable: true, get: function () { return userTransformer_1.UserTransformer; } });
var postTransformer_1 = require("./postTransformer.cjs");
Object.defineProperty(exports, "PostTransformer", { enumerable: true, get: function () { return postTransformer_1.PostTransformer; } });
var commentTransformer_1 = require("./commentTransformer.cjs");
Object.defineProperty(exports, "CommentTransformer", { enumerable: true, get: function () { return commentTransformer_1.CommentTransformer; } });
var gymTransformer_1 = require("./gymTransformer.cjs");
Object.defineProperty(exports, "GymTransformer", { enumerable: true, get: function () { return gymTransformer_1.GymTransformer; } });
var workoutsessionTransformer_1 = require("./workoutsessionTransformer.cjs");
Object.defineProperty(exports, "WorkoutSessionTransformer", { enumerable: true, get: function () { return workoutsessionTransformer_1.WorkoutSessionTransformer; } });
var exercisesetTransformer_1 = require("./exercisesetTransformer.cjs");
Object.defineProperty(exports, "ExerciseSetTransformer", { enumerable: true, get: function () { return exercisesetTransformer_1.ExerciseSetTransformer; } });
var exphistoryTransformer_1 = require("./exphistoryTransformer.cjs");
Object.defineProperty(exports, "ExpHistoryTransformer", { enumerable: true, get: function () { return exphistoryTransformer_1.ExpHistoryTransformer; } });
var userlevelTransformer_1 = require("./userlevelTransformer.cjs");
Object.defineProperty(exports, "UserLevelTransformer", { enumerable: true, get: function () { return userlevelTransformer_1.UserLevelTransformer; } });
var likeTransformer_1 = require("./likeTransformer.cjs");
Object.defineProperty(exports, "LikeTransformer", { enumerable: true, get: function () { return likeTransformer_1.LikeTransformer; } });
const machineTransformer_2 = require("./machineTransformer.cjs");
const userTransformer_2 = require("./userTransformer.cjs");
const postTransformer_2 = require("./postTransformer.cjs");
const commentTransformer_2 = require("./commentTransformer.cjs");
const gymTransformer_2 = require("./gymTransformer.cjs");
const workoutsessionTransformer_2 = require("./workoutsessionTransformer.cjs");
const exercisesetTransformer_2 = require("./exercisesetTransformer.cjs");
const exphistoryTransformer_2 = require("./exphistoryTransformer.cjs");
const userlevelTransformer_2 = require("./userlevelTransformer.cjs");
const likeTransformer_2 = require("./likeTransformer.cjs");
exports.toMachineDTO = machineTransformer_2.MachineTransformer.toDTO;
exports.toMachineEntity = machineTransformer_2.MachineTransformer.toEntity;
exports.toMachineDTOList = machineTransformer_2.MachineTransformer.toDTOList;
exports.toUserDTO = userTransformer_2.UserTransformer.toDTO;
exports.toUserEntity = userTransformer_2.UserTransformer.toEntity;
exports.toUserDTOList = userTransformer_2.UserTransformer.toDTOList;
exports.toPostDTO = postTransformer_2.PostTransformer.toDTO;
exports.toPostEntity = postTransformer_2.PostTransformer.toEntity;
exports.toPostDTOList = postTransformer_2.PostTransformer.toDTOList;
exports.toCommentDTO = commentTransformer_2.CommentTransformer.toDTO;
exports.toCommentEntity = commentTransformer_2.CommentTransformer.toEntity;
exports.toCommentDTOList = commentTransformer_2.CommentTransformer.toDTOList;
exports.toGymDTO = gymTransformer_2.GymTransformer.toDTO;
exports.toGymEntity = gymTransformer_2.GymTransformer.toEntity;
exports.toGymDTOList = gymTransformer_2.GymTransformer.toDTOList;
exports.toWorkoutSessionDTO = workoutsessionTransformer_2.WorkoutSessionTransformer.toDTO;
exports.toWorkoutSessionEntity = workoutsessionTransformer_2.WorkoutSessionTransformer.toEntity;
exports.toWorkoutSessionDTOList = workoutsessionTransformer_2.WorkoutSessionTransformer.toDTOList;
exports.toExerciseSetDTO = exercisesetTransformer_2.ExerciseSetTransformer.toDTO;
exports.toExerciseSetEntity = exercisesetTransformer_2.ExerciseSetTransformer.toEntity;
exports.toExerciseSetDTOList = exercisesetTransformer_2.ExerciseSetTransformer.toDTOList;
exports.toExpHistoryDTO = exphistoryTransformer_2.ExpHistoryTransformer.toDTO;
exports.toExpHistoryEntity = exphistoryTransformer_2.ExpHistoryTransformer.toEntity;
exports.toExpHistoryDTOList = exphistoryTransformer_2.ExpHistoryTransformer.toDTOList;
exports.toUserLevelDTO = userlevelTransformer_2.UserLevelTransformer.toDTO;
exports.toUserLevelEntity = userlevelTransformer_2.UserLevelTransformer.toEntity;
exports.toUserLevelDTOList = userlevelTransformer_2.UserLevelTransformer.toDTOList;
exports.toLikeDTO = likeTransformer_2.LikeTransformer.toDTO;
exports.toLikeEntity = likeTransformer_2.LikeTransformer.toEntity;
exports.toLikeDTOList = likeTransformer_2.LikeTransformer.toDTOList;
__exportStar(require("./nullableDate.cjs"), exports);
__exportStar(require("./bigintNumber.cjs"), exports);
