"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.toLikeDTOList = exports.toLikeEntity = exports.toLikeDTO = exports.toUserLevelDTOList = exports.toUserLevelEntity = exports.toUserLevelDTO = exports.toExpHistoryDTOList = exports.toExpHistoryEntity = exports.toExpHistoryDTO = exports.toExerciseSetDTOList = exports.toExerciseSetEntity = exports.toExerciseSetDTO = exports.toWorkoutSessionDTOList = exports.toWorkoutSessionEntity = exports.toWorkoutSessionDTO = exports.toGymDTOList = exports.toGymEntity = exports.toGymDTO = exports.toCommentDTOList = exports.toCommentEntity = exports.toCommentDTO = exports.toPostDTOList = exports.toPostEntity = exports.toPostDTO = exports.toUserDTOList = exports.toUserEntity = exports.toUserDTO = exports.toMachineDTOList = exports.toMachineEntity = exports.toMachineDTO = exports.LikeTransformer = exports.UserLevelTransformer = exports.ExpHistoryTransformer = exports.ExerciseSetTransformer = exports.WorkoutSessionTransformer = exports.GymTransformer = exports.CommentTransformer = exports.PostTransformer = exports.UserTransformer = exports.MachineTransformer = void 0;
var machine_transformer_1 = require("./machine.transformer.cjs.cjs");
Object.defineProperty(exports, "MachineTransformer", { enumerable: true, get: function () { return machine_transformer_1.MachineTransformer; } });
var user_transformer_1 = require("./user.transformer.cjs.cjs");
Object.defineProperty(exports, "UserTransformer", { enumerable: true, get: function () { return user_transformer_1.UserTransformer; } });
var post_transformer_1 = require("./post.transformer.cjs.cjs");
Object.defineProperty(exports, "PostTransformer", { enumerable: true, get: function () { return post_transformer_1.PostTransformer; } });
var comment_transformer_1 = require("./comment.transformer.cjs.cjs");
Object.defineProperty(exports, "CommentTransformer", { enumerable: true, get: function () { return comment_transformer_1.CommentTransformer; } });
var gym_transformer_1 = require("./gym.transformer.cjs.cjs");
Object.defineProperty(exports, "GymTransformer", { enumerable: true, get: function () { return gym_transformer_1.GymTransformer; } });
var workoutsession_transformer_1 = require("./workoutsession.transformer.cjs.cjs");
Object.defineProperty(exports, "WorkoutSessionTransformer", { enumerable: true, get: function () { return workoutsession_transformer_1.WorkoutSessionTransformer; } });
var exerciseset_transformer_1 = require("./exerciseset.transformer.cjs.cjs");
Object.defineProperty(exports, "ExerciseSetTransformer", { enumerable: true, get: function () { return exerciseset_transformer_1.ExerciseSetTransformer; } });
var exphistory_transformer_1 = require("./exphistory.transformer.cjs.cjs");
Object.defineProperty(exports, "ExpHistoryTransformer", { enumerable: true, get: function () { return exphistory_transformer_1.ExpHistoryTransformer; } });
var userlevel_transformer_1 = require("./userlevel.transformer.cjs.cjs");
Object.defineProperty(exports, "UserLevelTransformer", { enumerable: true, get: function () { return userlevel_transformer_1.UserLevelTransformer; } });
var like_transformer_1 = require("./like.transformer.cjs.cjs");
Object.defineProperty(exports, "LikeTransformer", { enumerable: true, get: function () { return like_transformer_1.LikeTransformer; } });
const machine_transformer_2 = require('transformers/machine.transformer');
const user_transformer_2 = require('transformers/user.transformer');
const post_transformer_2 = require('transformers/post.transformer');
const comment_transformer_2 = require('transformers/comment.transformer');
const gym_transformer_2 = require('transformers/gym.transformer');
const workoutsession_transformer_2 = require('transformers/workoutsession.transformer');
const exerciseset_transformer_2 = require('transformers/exerciseset.transformer');
const exphistory_transformer_2 = require('transformers/exphistory.transformer');
const userlevel_transformer_2 = require('transformers/userlevel.transformer');
const like_transformer_2 = require('transformers/like.transformer');
exports.toMachineDTO = machine_transformer_2.MachineTransformer.toDTO;
exports.toMachineEntity = machine_transformer_2.MachineTransformer.toEntity;
exports.toMachineDTOList = machine_transformer_2.MachineTransformer.toDTOList;
exports.toUserDTO = user_transformer_2.UserTransformer.toDTO;
exports.toUserEntity = user_transformer_2.UserTransformer.toEntity;
exports.toUserDTOList = user_transformer_2.UserTransformer.toDTOList;
exports.toPostDTO = post_transformer_2.PostTransformer.toDTO;
exports.toPostEntity = post_transformer_2.PostTransformer.toEntity;
exports.toPostDTOList = post_transformer_2.PostTransformer.toDTOList;
exports.toCommentDTO = comment_transformer_2.CommentTransformer.toDTO;
exports.toCommentEntity = comment_transformer_2.CommentTransformer.toEntity;
exports.toCommentDTOList = comment_transformer_2.CommentTransformer.toDTOList;
exports.toGymDTO = gym_transformer_2.GymTransformer.toDTO;
exports.toGymEntity = gym_transformer_2.GymTransformer.toEntity;
exports.toGymDTOList = gym_transformer_2.GymTransformer.toDTOList;
exports.toWorkoutSessionDTO = workoutsession_transformer_2.WorkoutSessionTransformer.toDTO;
exports.toWorkoutSessionEntity = workoutsession_transformer_2.WorkoutSessionTransformer.toEntity;
exports.toWorkoutSessionDTOList = workoutsession_transformer_2.WorkoutSessionTransformer.toDTOList;
exports.toExerciseSetDTO = exerciseset_transformer_2.ExerciseSetTransformer.toDTO;
exports.toExerciseSetEntity = exerciseset_transformer_2.ExerciseSetTransformer.toEntity;
exports.toExerciseSetDTOList = exerciseset_transformer_2.ExerciseSetTransformer.toDTOList;
exports.toExpHistoryDTO = exphistory_transformer_2.ExpHistoryTransformer.toDTO;
exports.toExpHistoryEntity = exphistory_transformer_2.ExpHistoryTransformer.toEntity;
exports.toExpHistoryDTOList = exphistory_transformer_2.ExpHistoryTransformer.toDTOList;
exports.toUserLevelDTO = userlevel_transformer_2.UserLevelTransformer.toDTO;
exports.toUserLevelEntity = userlevel_transformer_2.UserLevelTransformer.toEntity;
exports.toUserLevelDTOList = userlevel_transformer_2.UserLevelTransformer.toDTOList;
exports.toLikeDTO = like_transformer_2.LikeTransformer.toDTO;
exports.toLikeEntity = like_transformer_2.LikeTransformer.toEntity;
exports.toLikeDTOList = like_transformer_2.LikeTransformer.toDTOList;
__exportStar(require("./nullableDate.cjs.cjs"), exports);
__exportStar(require("./bigintNumber.cjs.cjs"), exports);
