"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authController_1 = require('controllers/authController');
const auth_1 = require('middlewares/auth');
const recaptcha_enterprise_1 = require('utils/recaptcha-enterprise');
const router = (0, express_1.Router)();
router.post("/login", (0, recaptcha_enterprise_1.recaptchaEnterpriseMiddleware)("LOGIN", 0.5), authController_1.login);
router.post("/register", (0, recaptcha_enterprise_1.recaptchaEnterpriseMiddleware)("REGISTER", 0.7), authController_1.register);
router.post("/refresh", authController_1.refreshToken);
router.post("/logout", authController_1.logout);
router.get("/check", auth_1.authMiddleware, authController_1.checkAuth);
router.post("/find-id", authController_1.findId);
router.post("/find-password", authController_1.findPassword);
router.post("/find-id-simple", authController_1.findIdSimple);
router.post("/reset-password-simple-step1", authController_1.resetPasswordSimpleStep1);
router.post("/reset-password-simple-step2", authController_1.resetPasswordSimpleStep2);
router.post("/find-id/verify-user", authController_1.findIdStep1);
router.post("/find-id/verify-code", authController_1.findIdStep2);
router.post("/reset-password/verify-user", authController_1.resetPasswordStep1);
router.post("/reset-password/verify-code", authController_1.resetPasswordStep2);
router.post("/reset-password/complete", authController_1.resetPasswordStep3);
exports.default = router;
