"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require('middlewares/auth');
const commentController_1 = require('controllers/commentController');
const router = (0, express_1.Router)();
const commentController = new commentController_1.CommentController();
router.get("/:id", commentController.getCommentsByPostId);
router.post("/:id", auth_1.authMiddleware, commentController.createComment);
router.put("/:id", auth_1.authMiddleware, commentController.updateComment);
router.delete("/:id", auth_1.authMiddleware, commentController.deleteComment);
exports.default = router;
