"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const gymController_1 = require('controllers/gymController');
const router = (0, express_1.Router)();
router.get("/", gymController_1.getAllGyms);
router.get("/:id", gymController_1.getGymById);
router.get("/search", gymController_1.searchGyms);
router.get("/search/location", gymController_1.getGymsByLocation);
router.post("/update", gymController_1.updateGymData);
exports.default = router;
