"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const postController_1 = require('controllers/postController');
const auth_1 = require('middlewares/auth');
const router = (0, express_1.Router)();
const postController = new postController_1.PostController();
router.get("/", postController.getAllPosts);
router.get("/categories", postController.getCategories);
router.get("/categories/live", postController.getCategoriesLive);
router.get("/my", auth_1.authMiddleware, postController.getMyPosts);
router.get("/:id", postController.getPostById);
router.post("/", auth_1.authMiddleware, postController.createPost);
router.put("/:id", auth_1.authMiddleware, postController.updatePost);
router.delete("/:id", auth_1.authMiddleware, postController.deletePost);
exports.default = router;
