"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const workoutController_1 = require('controllers/workoutController');
const auth_1 = require('middlewares/auth');
const rateLimiter_1 = require('middlewares/rateLimiter');
const router = (0, express_1.Router)();
const workoutController = new workoutController_1.WorkoutController();
router.get("/plans", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), workoutController.getUserPlans);
router.post("/plans", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.createPlan);
router.put("/plans/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.updatePlan);
router.delete("/plans/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.deletePlan);
router.get("/sessions", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), workoutController.getUserSessions);
router.post("/sessions", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.startSession);
router.post("/sessions/:id/complete", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.completeSession);
router.get("/goals", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), workoutController.getUserGoals);
router.post("/goals", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.createGoal);
router.put("/goals/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.updateGoal);
router.delete("/goals/:id", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 10), workoutController.deleteGoal);
router.get("/progress", auth_1.authMiddleware, (0, rateLimiter_1.rateLimiter)(60000, 30), workoutController.getProgress);
exports.default = router;
