// ============================================================================
// 런타임 검증 및 데이터 변환 유틸리티
// ============================================================================

const { isUserDTO,
  isWorkoutPlanDTO,
  isWorkoutSessionDTO,
  isWorkoutGoalDTO,
  isMachineDTO,
  isExerciseSetDTO,
  isGymDTO,
  isUserLevelDTO,
  isUserStreakDTO,
  isDTOResponse,
  isDTOPaginatedResponse,
  validateUserDTO,
  validateWorkoutPlanDTO,
  validateWorkoutSessionDTO,
  validateWorkoutGoalDTO,
  validateMachineDTO,
  validateExerciseSetDTO,
  safeParseUserDTO,
  safeParseWorkoutPlanDTO,
  safeParseWorkoutSessionDTO,
  safeParseWorkoutGoalDTO,
  safeParseMachineDTO,
  safeParseExerciseSetDTO,
  isString,
  isNumber,
  isBoolean,
  isDateString,
  isArray,
  isObject,
  isEmail,
  isPhoneNumber,
  isUrl,
  isPositiveNumber,
  isNonNegativeNumber,
  isPositiveInteger,
  isNonNegativeInteger,
 } = require('../types/guards')